name = "grw"
version = "0.1.0"
defaultTargets = ["Grw"]

[[lean_lib]]
name = "Grw"

[[lean_lib]]
name = "GrwTest"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.17.0-rc1"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.17.0-rc1"
